### PR TITLE
configuration tool for tdnf

### LINKED ISSUE #265: tdnf makecache is crashing
➜  yum.repos.d cat Artifactory.repo
[Artifactory] name=Artifactory baseurl=https://packages.vmware.com/photon/$releasever/photon_debuginfo_$releasever_$basearch enabled=0 gpgcheck=0
➜  ~ tdnf makecache
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
Refreshing metadata for: 'Test repo'      3581   100%
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64)'
[1]    9745 segmentation fault (core dumped)  tdnf makecache
➜  ~ echo $?
139
➜  ~ rpm -qa  tdnf
tdnf-3.1.4-2.ph3.x86_64
➜  ~

(gdb) n
230	    for(pRepo = pTdnf->pRepos; pRepo; pRepo = pRepo->pNext)
(gdb) n
234	        if ((strcmp(pRepo->pszName, "@cmdline") == 0) ||
(gdb) p pRepo->pszName <-- This is NULL which we are sending to strcmp causing the segmentation fault.
$14 = 0x0

### PR DESCRIPTION
**Pull request by oliverkurth**
This creates a configuration tool for tdnf to edit the main and repository configurations.

The general syntax is:
`tdnf-config [-c|--config <file>][-f|--file <file>][-j|--json]`

Commands:

## edit

Syntax: `edit main|<repo> [[key=value]...]`

Change an existing config file or repo configuration. Example:
`tdnf-config edit photon enabled=1`

Multiple variables can be specified:
`tdnf-config edit photon enabled=1 gpgcheck=1`

## create

Syntax: `create main|<repo> [[key=value]...]`

Create a new repository configuration. Config options can be specified at the same time. Example:

`tdnf-config create foo baseurl=http://foo.bar.com enabled=1`

This would generate this repo config:
```
# cat /etc/yum.repos.d/foo.repo 
[foo]
baseurl = http://foo.bar.com
enabled = 1
```

## get

Syntax: `get main|<repo> key`

Retrieve a value. Example:
```
# tdnf-config get main clean_requirements_on_remove gpgcheck
0
```

## remove

Syntax: `remove main|<repo> key`

Remove an entry.

## removerepo

Syntax: `removerepo <repo>`

Example:
`tdnf-config removerepo foo`

## dump

Syntax: `dump main|<repo>`

Dump contents of a repo config or the main config. Example:
```
# ./bin/tdnf-config dump photon       
[photon]
name = VMware Photon Linux $releasever ($basearch)
baseurl = https://packages.vmware.com/photon/$releasever/photon_$releasever_$basearch
gpgkey = file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY-4096
gpgcheck = 1
enabled = 1
skip_if_unavailable = 1
skip_md_filelists = 1
```
Useful here is the `-j` option for json output. The output is compact, use `jq` for pretty output:
```
# ./bin/tdnf-config -j dump photon | jq .
{
  "photon": {
    "name": "VMware Photon Linux $releasever ($basearch)",
    "baseurl": "https://packages.vmware.com/photon/$releasever/photon_$releasever_$basearch",
    "gpgkey": "file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY-4096",
    "gpgcheck": "1",
    "enabled": "1",
    "skip_if_unavailable": "1",
    "skip_md_filelists": "1",
    "foo": "bar"
  }
}
```

### -c|--config <file>

Specify the main config file (default is `/etc/tdnf/tdnf.conf`). This is used to find the directory for repo configs if specified.

### -f|--file <file>

Specify the file to be used for the repo configuration. By default, for existing repos, all `*.repo` files in the repo config dir (`/etc/yum.repos.d` by default)will be searched for a matching repo. For creating a repo, a new file with the name repo id plus the extension `.repo` will be created.

## -j|--json

Applies to the `dump` command. Format the output in json (compact) format.

### CODE REVIEW

File: client/config.c [hunk 1]
```diff
@@ -64,88 +74,148 @@ TDNFReadConfig(
...
+        if ((cn->name[0] == '.') || (cn->value == NULL))
+            continue;
 
-    dwError = TDNFReadKeyValue(
-                  pSection,
-                  TDNF_CONF_KEY_DISTROVERPKG,
-                  TDNF_DEFAULT_DISTROVERPKG,
-                  &pConf->pszDistroVerPkg);
-    BAIL_ON_TDNF_ERROR(dwError);
+        if (strcmp(cn->name, TDNF_CONF_KEY_INSTALLONLY_LIMIT) == 0)
```
Comment (ntsbtz) [inline client/config.c:121]: Can we replace with switch

File: client/config.c [hunk 2]
```diff
@@ -64,88 +74,148 @@ TDNFReadConfig(
...
+        }
+    }
 
-    dwError = TDNFReadKeyValueStringArray(
-                  pSection,
-                  TDNF_CONF_KEY_EXCLUDE,
-                  &pConf->ppszExcludes);
-    BAIL_ON_TDNF_ERROR(dwError);
+    /* if plugins are not enabled explicitely,
+       we have to disable them because it's the default */
```
Comment (ntsbtz) [inline client/config.c:214]: If this should be enable explicitly. Then by default it should be disable.

File: client/plugins.c [hunk 3]
```diff
@@ -228,43 +239,58 @@ _TDNFLoadPluginConfig(
...
 
     if(IsNullOrEmptyString(pszConfigFile) || !ppPlugin)
     {
         dwError = ERROR_TDNF_INVALID_PARAMETER;
         BAIL_ON_TDNF_ERROR(dwError);
     }
 
-    dwError = TDNFReadConfigFile(pszConfigFile, 0, &pData);
-    BAIL_ON_TDNF_ERROR(dwError);
+    mod_ini = find_cnfmodule("ini");
```
Comment (ntsbtz) [inline client/plugins.c:251]: Need a null check

File: client/repolist.c [hunk 4]
```diff
@@ -438,220 +442,172 @@ TDNFEventRepoReadConfigStart(
...
-    char *pszRepo = NULL;
     uint32_t dwError = 0;
     char *pszMetadataExpire = NULL;
 
     PTDNF_REPO_DATA pRepos = NULL;
     PTDNF_REPO_DATA pRepo = NULL;
 
-    PCONF_DATA pData = NULL;
-    PCONF_SECTION pSections = NULL;
+    struct cnfnode *cn_conf, *cn_section, *cn;
```
Comment (ntsbtz) [inline client/repolist.c:464]: Initialization and null check required

File: client/repolist.c [hunk 5]
```diff
@@ -438,220 +442,172 @@ TDNFEventRepoReadConfigStart(
...
-        BAIL_ON_TDNF_ERROR(dwError);
-
-        TDNF_SAFE_FREE_MEMORY(pszMetadataExpire);
-        pszMetadataExpire = NULL;
+        if (errno != 0)
+        {
+            dwError = errno;
+            BAIL_ON_TDNF_SYSTEM_ERROR(dwError);
+        }
+        else
```
Comment (ntsbtz) [inline client/repolist.c:481]: condition is not required

File: client/repolist.c [hunk 6]
```diff
@@ -438,220 +442,172 @@ TDNFEventRepoReadConfigStart(
...
-                      TDNF_REPO_KEY_SKIP_MD_OTHER,
-                      TDNF_REPO_DEFAULT_SKIP_MD_OTHER,
-                      &pRepo->nSkipMDOther);
-        BAIL_ON_TDNF_ERROR(dwError);
+        for(cn = cn_section->first_child; cn; cn = cn->next)
+        {
+            if ((cn->name[0] == '.') || (cn->value == NULL))
+                continue;
 
+            if (strcmp(cn->name, TDNF_REPO_KEY_ENABLED) == 0)
```
Comment (ntsbtz) [inline client/repolist.c:507]: same as above replace with switch

File: client/config.c [hunk 7]
```diff
@@ -64,88 +74,148 @@ TDNFReadConfig(
...
+    pConf->nKeepCache = 0;
 
-    dwError = TDNFReadKeyValueBoolean(
-                  pSection,
-                  TDNF_CONF_KEY_GPGCHECK,
-                  0,
-                  &pConf->nGPGCheck);
-    BAIL_ON_TDNF_ERROR(dwError);
+    register_ini(NULL);
+    mod_ini = find_cnfmodule("ini");
```
Comment (ntsbtz) [inline client/config.c:91]: Init and null check

File: tools/config/main.c [hunk 8]
```diff
@@ -0,0 +1,477 @@
...
+        struct cnfnode *cn_root = NULL;
+
+        while (optind + argcount < argc)
+            argcount++;
+
+       	/*
+        * Find the action.
+        */
+        action = argv[optind];
+        if(strcmp(action, "edit") == 0 || strcmp(action, "create") == 0) {
```
Comment (ntsbtz) [inline tools/config/main.c:319]: can we have all option like edit, create, modify as a macros

File: tools/config/main.c [hunk 9]
```diff
@@ -0,0 +1,477 @@
...
+                    if (rc != 0)
+                        fail(ERR_SYSTEM, "failed to write file '%s': %s (%d)", filename, strerror(errno), errno);
+
+                    safe_free(filename);
+                } else
+                    cnfmodule_unparse(mod_ini, stdout, cn_root);
+
+                destroy_cnftree(cn_root);
+            }
+        } else if (strcmp(action, "get") == 0) {
```
Comment (ntsbtz) [inline tools/config/main.c:373]: same as above macro

File: tools/config/main.c [hunk 10]
```diff
@@ -0,0 +1,477 @@
...
+
+            cn_root = get_repo_root(main_config, repo, &filename);
+
+            if (cn_root) {
+                remove_repo(cn_root, repo);
+                if (filename) {
+                    if (cn_root->first_child) {
+                        rc = write_file(cn_root, filename);
+                        if (rc != 0)
+                            fail(ERR_SYSTEM, "failed to write file '%s': %s (%d)", filename, strerror(errno), errno);
```
Comment (ntsbtz) [inline tools/config/main.c:435]: can we have all error strings in a macro so printing will be more readable

**Review by ntsbtz — APPROVED** [review]
Have some minor comments else LGTM !!!

File: client/config.c (hunk 1 above)
Comment (oliverkurth) [reply client/config.c:121]: This is `strcmp()`. This cannot be done with `switch`.

File: client/repolist.c (hunk 6 above)
Comment (oliverkurth) [reply client/repolist.c:507]: Cannot use `switch` for `strcmp()`.

File: tools/config/main.c (hunk 8 above)
Comment (oliverkurth) [reply tools/config/main.c:319]: I don't like that. It makes it harder to read because then we'd need to look up how those macros are defined.

File: tools/config/main.c (hunk 10 above)
Comment (oliverkurth) [reply tools/config/main.c:435]: Same here - macros make it harder to read.

File: client/repolist.c (hunk 5 above)
Comment (oliverkurth) [reply client/repolist.c:481]: Can you elaborate? Which condition is not needed and why?

File: client/repolist.c (hunk 4 above)
Comment (oliverkurth) [reply client/repolist.c:464]: `cn_conf` is checked on assignment. The others are assigned before usage.

File: client/config.c (hunk 2 above)
Comment (oliverkurth) [reply client/config.c:214]: I made the comment because the logic is confusing. By default, we want plugins to be disabled. However, in `plugins.c` we check if the setting "noplugins" (`TDNF_CONF_KEY_NO_PLUGINS`) exists (also, disregarding the value) - but if we don't explicitly add it here, plugins would be enabled.

File: client/repolist.c (hunk 5 above)
Comment (ntsbtz) [reply client/repolist.c:481]: Sorry, my bad BAIL_ON_TDNF_SYSTEM_ERROR and BAIL_ON_TDNF_ERROR are different
